basic_settings:
  site_title: Edmondson Park Education and Care
  favicon_image: /favicon.ico

menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'
    - title: 'Contact'
      url: '/contact'

hero_settings:
  overlay_opacity: 0.8

post_settings:
  grid_spacing: 10

contact_settings:
  form_action: 'https://formspree.io/fiona@educationandcare.org'
  confirmation_url: '/thanks'
  email_subject: 'EPEC contact form submission'
  send_button_text: 'Send Message'

contact_details:
  address: '125 Jardine Drive, Edmondson Park NSW 2174'
  address_icon: 'map-pin'
  email: 'edpark@educationandcare.org'
  email_icon: 'mail'
  phone: '(02) 9607 9000'
  phone_icon: 'phone'

social_settings:
  facebook_url: 'https://www.facebook.com/edparkeducationandcare/'
  twitter_url: ''
  instagram_url: ''
  youtube_url: ''

color_settings:
  background_color: '#FFFFFF'
  background_alt_color: '#F4F5F6'
  text_dark_color: '#2A2F36'
  text_medium_color: '#6C7A89'
  text_light_color: '#ABB7B7'
  accent_color: '#3498DB'
  border_color: '#DDDDDD'
  hero_background_color: '#132930'
  hero_text_color: '#FFFFFF'
  error_color: '#D64541'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Muli:300,400,600,700" rel="stylesheet">'
  title_font: '"Muli", sans-serif'
  body_font: '"Muli", sans-serif'
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 25
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 15
    large_size: 17
    weight: 600
    letter_spacing: 0
  h1:
    small_size: 35
    medium_size: 45
    large_size: 60
    weight: 700
    letter_spacing: -0.03
    line_height: 1.2
  h2:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 600
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 18
    medium_size: 20
    large_size: 22
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
